import { useState } from 'react'
import './Page.css'
import Navbar from '../components/AppBar'

function History() {
  return (
    <>
      <Navbar/>
      <section id="center">
        <div>
          <h1>The Sonic History of La Jolla</h1>
        </div>
        <div>
          <h3> Pre-1887</h3>
          <p>Early accounts of La Jolla praise it for its “pristine emptiness” (3) – a picturesque, largely treeless landscape of low-lying coastal shrubs, “sweet-smelling with wildflowers and aromatic bushes” (3). According to early resident Ellen Mills, “La Jolla was just a beautiful expanse of grey-green sagebrush and darker chaparral from Mt. Soledad to the Cove” (6). Before its first permanent settlements were built, the area was a popular day trip destination for San Diego residents, who would come at low tide to admire the dramatic coastline and gather the shells and mosses that lined the seashore.</p>
          <br/>
          <p>In those days, the sounds of the gentle sea breeze and the waves crashing against the cliffs must have defined La Jolla’s soundscape to an even greater extent than they do today. The sonic contributions of flora and fauna are not to be neglected; early writings note the presence of blue jays, owls, road runners, herons, and seagulls, as well as an abundance of skunks, rabbits, rattlesnakes, ground squirrels, and various insects. An account by Ellen Browning Scripps reminisces about air “resonant with the song of the meadow lark; the drone of the bees, the chirp of the cricket and the hum of aerial insect life” (5).</p>
          <br/>
          <h3>1880s-1890s</h3>
          <p>La Jolla’s first full-time residents built homes in 1887; by 1893, the town boasted a new hotel, railway connection to San Diego, and a few hundred residents. This rapid growth brought about many changes to village life as La Jolla transitioned from an undeveloped vacation destination to a lively small town. In addition to the ever-present roar of the sea,  sounds typical of this time period might include the vocalizations and hoofbeats of the town’s many cows and horses on dirt paths, the creaking of wooden stagecoach wheels, and the “roar and whistle” (3) of the steam engine. Axes, saws, and other woodworking tools employed for the cutting and splitting of wood would have also been prevalent, both for the heating of homes and the construction of the redwood cottages typical of the time.</p>
          <br/>
          <p>The turn of the century also brought with it the first automobiles; while these were not common in La Jolla at the time, some of its more eccentric residents embraced the new technology. Dr. Joshua Longstreth Baily Jr. identifies one Mr. Auberon Herbert as “the first resident of La Jolla to own an automobile”, who “frequently went out driving but did not so frequently drive back again” (1). The vehicle was so unreliable that when it inevitably broke down, it would have to be towed back by mule! For a brief stretch of time, it was not unusual for the cracking of whips and rumbling of engines to coexist on village streets.</p>
          <br/>
          <p>Despite the real estate boom and advancements in transportation, the sounds of the largely unspoilt nature that surrounded La Jolla must have still dominated its soundscape. One significant ecological shift that occurred around this time was the planting of trees; allegedly, “one thousand palms, one thousand cedar, eucalyptus, and other trees” (6). The scarcity of water in La Jolla’s early days means many of these plants did not survive, but those that did would come to dominate La Jolla streets. One can imagine the array of new sounds caused by the introduction of trees into a formerly unforested environment: the creaking of branches, leaves rustling in the wind, and the birds and insects that could now call them home.</p>
          <br/>
          <h3>1900s - 1910s</h3>
          <p>A remarkable shift in the soundscape must have occurred when, due to the growing popularity of automobiles, La Jolla’s streets and sidewalks were paved. This process began in 1915 and continued into the 1920s, but was met with protest by La Jolla residents worried about mounting costs and the threat of sore feet. Thus, the soft crunch of footsteps on dirt paths gave way to the harsher sounds of concrete.</p>
          <br/>
          <p>La Jolla’s modernization was already well on its way by this time. In 1908, a natural gas engine train began to service La Jolla, but its unreliability meant the old steam engine was never fully retired until the railway was discontinued in 1919. In 1909, natural gas first became available to residents, followed by electricity in 1911 (with a whopping 4 customers). With electrification came perhaps the first of the industrial drones and hums that are now a ubiquitous, if subtle, component of the La Jolla soundscape: the 60 Hz noise from commercial power lines.</p>
          <br/>
          <p>Following the United States’s entrance into World War I in 1917, military activity in La Jolla expanded significantly. The rapid construction of Camp Kearny in nearby Linda Vista and the 24,000 troops that followed brought with them “the cadence of marching feet, the reports of rifles, and the clatter of mounted soldiers” (4). Although Camp Kearny was far from La Jolla proper, the explosives used to create trenches and foxholes could be heard from afar, and the road between La Jolla and Torrey Pines was paved to facilitate the transport of soldiers and materials. Significant construction was required to provide the camp with electricity, natural gas, communications, and railway services, and the laborers, mules, and motor vehicles put to the task must have also contributed to La Jolla’s first wartime soundscape.</p>
          <br/>
          <p>During World War I, the tolling of bells took on meanings beyond simply telling the time of day. On October 15th, 1917, La Jolla’s first curfew bell was rung to keep children off the streets in the evenings. In contrast, the daily ringing of “victory bells” at noon signaled hope and prayers for peace. On Armistice Day, the violent sounds of fire and explosions were used to signal joy. A rather colorful editorial from the La Jolla Journal lists “pyrotechnics, oral and otherwise, punctuat[ing] the passing hours”, a “triumphant preliminary procession prepar[ing] to pace”, and “the last lurid pop of the previously prodigious pyre in the playgrounds” (6) in its description of the day’s festivities.</p>
          <br/>
          <h3>1920s</h3> 
          <p>Many affectionate recollections of 1920s La Jolla claim this period to be the town’s “Golden Age”. The town prospered during this time, and many developments and expansions went underway.  An electric streetcar connection to downtown San Diego and Pacific Beach was established in 1924, providing memorable trips to La Jolla residents commuting to downtown San Diego. Resident Norma Hacker reminisces on her morning commute: </p>
          <br/>
          <p>“ ‘our crowd’ even stood when necessary to be back where the laughter was… Those early mornings with the sun striking down through the tall groves of buildings which lined Broadway were happy, silly times. We laughed at nothing and at everything”. (3)</p>
          <br/>
          <p>The primary pastimes of La Jolla residents at this time were tennis, golf, and swimming in the ocean. These were athletic as well as social pursuits, and one can imagine the swishing of racquets and buzz of conversation emanating from the La Jolla Beach and Tennis Club. The streets must also have been rich with the sounds of daily life: perhaps starting with the clinking of milk bottles, followed by door-to-door salesmen, garbage collectors, grocery deliveries, and residents going about their days on foot, car, or horseback. The population had since grown to about four thousand people, and the shops, schools, and social clubs in town were by then well-established. For many children, the ringing of the high school bell– audible from several blocks away (3) – established the rhythm of daily life.</p>
          <br/>
          <p>The town’s rapid growth did not suppress the dominance of natural sounds in the La Jolla of the 1920s. Hacker recalls that “It was a world of sound and taste and smell. Of lovely vistas as well but… they do not evoke the memories the other senses bring. Over all, it was the sound of the sea, breaking against the cliff, surging up the beaches and swirling in the golden cove. Sometimes it was merely a faintly heard presence but when there was a storm and the waves crashed against the land, everyone would bundle up against the cold and go down to stand and watch the spray… ”. (3)</p>
          <br/>
          <p>In the spring, frogs dominated the soundscape at dusk: “with the coming of darkness, their falsetto croaking blended with the chirping of crickets”, followed by “owls, mice, and pack rats scurrying about” (3) at night. In the daytime, one venturing inland might hear how “doves cooed and coveys of quail whirred up to swirl away and then emit their ka-KA-ka cries”; closer to the ocean, the streets “sounded with breaking waves, the cries of gulls and the quarter-hourly Westminster chimes from the bell tower” (3). By this time, eucalyptus canopies shaded Ivanhoe Avenue and Wall Street, contributing the papery sound of their leaves and bark, rattling and peeling in the wind.</p>
          <br/>
          <p>The presence of livestock was still fairly common at the time, and the vacant fields of wild oats and elderberries surrounding the town were criss-crossed by cowpaths (as were the beaches!). Chaffee King Castleton’s reflections on La Jolla’s equestrian past highlight the town’s closeness to nearby open space:</p>
          <br/>
          <p>“Besides tennis, and swimming at the Cove, La Jolla to many meant ‘horses’... One might ride out from Stevie’s in those days on a dear lively little horse named Billy, with no saddle, just bridle and surcingle. One cantered up Pearl Street into Fay and directly into the wilds of Muirlands… Just heather, sage, chemise everlasting, and the flickering shade of a few eucalyptus in lovely sweetness, quietness and solitude.” (3) </p>
          <br/>
          <h3>1930s - 1940s</h3>
          <p>In 1940, La Jolla’s “top-heavy, creaky, old fashioned streetcar” (3) was retired. During its final trip, the motorman let passengers commemorate the moment with the streetcar’s most distinctive sounds: </p>
          <br/>
          <p>“He gave us permission… to blow the whistle and ring the bell on the back end of the car all the way. We whistled and jangled all the way through Mission Beach, Pacific Beach, and down Fay Street, arriving at the La Jolla terminal around 2 a.m. We hoped we had waked [sic] them up along the way. They didn’t know it but it wasn’t just a streetcar going by. It was the passing of an era”. (3) </p>
          <br/>
          <p>The streetcar’s whistles, rattles, and wheezing brakes gave way to the comparatively muted sounds of a new bus service (“which currently takes almost as much time from San Diego to La Jolla as it took by horse drawn stage one hundred years ago” (3) ).</p>
          <br/>
          <p>As in much of the rest of the world, the Great Depression and World War II had significant effects on La Jolla’s economy and industrial capacity. The nearby military bases Camp Callan and Camp Matthews joined Camp Kearny, and “the whole region became a military zone”. Camp Callan in particular controlled the majority of the La Jolla cliffs, where heavy artillery training took place. “In 1941, the camp started out with nine 155mm guns on the Knoll; these could fire 95 pound missiles nearly ten miles. When they were fired, the earth shook, and so did the 14-member gun crew” (7). These were shortly succeeded by anti-aircraft guns; at nearby Camp Matthews, soldiers were trained on 60mm mortars, hand grenades, bazookas, and flame throwers. The quiet, peaceful soundscape La Jolla knew in the 20s was dramatically altered by these military exercises and the influx of soldiers populating Camp Callan.</p>
          <br/>
          <p>Today, there is little left of Camp Callan; the majority of it was disassembled after the war in order to repurpose its lumber for veterans’ housing. UC San Diego, the Salk Institute for Biological Studies, and the Torrey Pines Golf Course sit on its remains.</p>
          <br/>
          <h3>1950s - 1960s</h3>
          <p>The postwar years saw tremendous expansion. Neighborhoods surrounding La Jolla Park, such as Bird Rock, Mt. Soledad, and the Muirlands, were developed and absorbed into the town of La Jolla. Construction noise, the tolling of bells in the many new churches, and the dwindling presence of nearby open space rapidly altered La Jolla’s sights and sounds. This expansion wasn’t just residential. Faced with a sudden decrease in demand and anxious to avoid another recession, the corporations that had made San Diego an industrial powerhouse during World War II worked to establish peacetime purposes for their capabilities. Most notably, General Dynamics established its General Atomics division in 1955 with the motto “harnessing the power of nuclear technologies for the benefit of man” (2). The General Atomics campus was built in the hills east of Camp Callan, just blocks away from the north edge of UC San Diego’s present-day campus.</p>
          <br/>
          <p>Backed by General Atomics’s founder, John Jay Hopkins, Roger Revelle, then Director of the Scripps Institution of Oceanography, and various San Diego civic leaders, plans for a new University of California campus in La Jolla took shape in the late 1950s. Friction between Revelle and UC Regent Edwin Pauley characterized most of the deliberation over the new campus’s location and scope of instruction. Interestingly, the question of noise pollution played a significant role here. Regent Pauley claimed that the aviation noise generated by the nearby Naval Air Station Miramar made the proposed site (which to this day lies directly under the facility’s flight path) unsuitable for an institution of higher learning. In the 1950s, the NAS Miramar was preoccupied with training fighter jet pilots for the Korean War; the cacophony caused by the roaring engines and afterburners (2) of supersonic flight were then characteristic of the region.</p>
          <br/>
          <p>Revelle eventually triumphed over Pauley, and UC San Diego was finally established in 1960. Years of UC-affiliated construction projects followed, including UCSD’s First (now Revelle) and Second (now Muir) Colleges; the Coast Apartments, originally built to house married SIO graduate students; the (unaffiliated, but very close by) Salk Institute For Biological Studies; and the UCSD Medical Campus and Veterans Administration hospital. The hills surrounding the General Atomics campus were rezoned for research and development use, attracting further construction projects from the private sector; the region is now dense with biotechnology offices and labs. Due to the University’s constant expansion and the industrial and residential projects it has attracted, the sounds of construction have since been an inescapable part of the area’s soundscape.</p>
          <br/>
          <h3>1970s - Present day</h3>
          <p>In the years since the University’s founding, the sonic characteristics of La Jolla and the neighboring UCSD campus have continued to evolve, with growing industrial noise at the forefront of these changes. Perhaps most significant is the completion of the San Diego portion of Interstate 5 in the late 60s, followed by its widening from a four-lane to an eight-lane highway. The ceaseless drone of traffic noise, modulated over the years by changing engines, mufflers, and now the advent of electric motors, is a constant presence; at rush hour, a careful ear can even discern it against the sound of the waves by the seaside. This is far from the only contribution to UCSD’s noise floor. Various mechanical drones and hums from the likes of the supercomputer center, building air conditioning units, the Central Utilities Plant, and the University’s electrical infrastructure underscore every minute of daily life on campus. Despite their pervasive nature, these sounds are often only noticeable late at night and early in the morning, when one would expect something approaching total silence.</p>
          <br/>
          <p>Beginning in the 1970s and reaching its peak in the 80s and 90s, the empty fields surrounding the University saw a boom in residential development; the resulting complexes now form a bulk of the off-campus housing options available to students. The gas stations, shopping centers, schools, and recreational facilities built to support these residential developments have further stifled the sounds of nature that long dominated these areas. To counteract this, pockets of protected land– most notably the Mesa, Rose, and Sumner canyons– infuse the urban landscapes that border them with the sounds of local flora and fauna. Among their more vocal residents are coyotes and many species of songbird, whose territories, both physical and acoustic, frequently overlap with human ones. The town of La Jolla now hosts tens of thousands of inhabitants, and though the center has maintained its charm, population growth, changing infrastructure, and outward expansion have hardened its sonic characteristics and further distanced it from the nature that used to envelop it.</p>
          <br/>
          <p>Aviation noise remains a prominent feature of the UCSD campus and surrounding area. Although NAS Miramar has since moved to Virginia, the land has turned into a Marine Corps Air Station. Anyone who has spent time on campus, particularly during the summer months, is well aware that Miramar is still an active air station! The frequent passage of helicopters and fighter jets is now a commonplace (but still controversial) occurrence on campus. Although the roar of military aircraft is somewhat muffled inside University buildings, frequent overhead flights make outdoor meetings challenging, despite the attractive charms of La Jolla’s pleasant weather…</p>
          <br/>
          <p>Speaking from personal experience: the extent to which various buildings along the MCAS flightpath withstand aviation noise is an interesting way to speculate about developments in architectural noise suppression technologies. In many of UCSD’s newer buildings and lecture halls, fighter jet fly-bys appear only as distant rumbles. Some of the high-rises are not so comfortable; the first time I heard the Blue Angels from the thirteenth floor of Seventh College’s East Tower, the walls shook so violently that I thought an earthquake had started! At the most disappointing end of the noise abatement spectrum, General Atomics’s iconic Building 2 (which dates back to the mid-50s) is a two-story building that completely fails to muffle engine noise. When jets pass overhead, the sound is so deafening that all meetings and conversations must be put on pause for a matter of seconds.</p>
          <br/>
          <h2>Bibliography</h2>
          <p>(1) Baily, Joshua Longstreth. La Jolla’s Early Society  / Dr. Joshua Longstreth Baily, Jr. [The Author], 1961.</p>
          <br/>
          <p>(2) Fisher, Jack C. Preparing the Soil for UC San Diego : Land, Thoroughfares, and Local Expectations  / Jack C. Fisher. [UC San Diego Library], 2017.</p>
          <br/>
          <p>(3) La Jolla Historical Society. Inside La Jolla  / by La Jolla Historical Society. 1st ed., Centennial ed, The Society, 1988.</p>
          <br/>
          <p>(4) Martin, John. “Patriotism and Profit: San Diego’s Camp Kearny.” The Journal of San Diego History, vol. 58, no. 4, 2012.</p>
          <br/>
          <p>(5) McClain, Molly. “The La Jolla of Ellen Browning Scripps.” The Journal of San Diego History, vol. 56, no. 1, 2010.</p>
          <br/>  
          <p>(6) Randolph, Howard S. F. La Jolla : Year by Year  / by Howard S.F. Randolph. [San Diego, Calif.], 1946.</p>
          <br/>
          <p>(7) Ticho, Suzy. Sumner Canyon  / Suzy Ticho. [S. Ticho], 2009.</p>
          <br/>
        </div>
      </section>
    </>
  )
}

export default History
